# بسم الله الرحمن الرحيم
version: 2.1

jobs:
  deploy: 
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout

      # Download and cache dependencies

      - run: 
          name: Install Dependencies
          command: npm install
      - run:
          name: Deploy at Netlify 
          command: npm run deploy
      #- run: 
       #   name: Server Live
        #  command: npm run live
workflows:
  build_deploy:
    jobs: 
      - deploy