# بسم الله الرحمن الرحيم
version: 2.1

jobs:
  deploy: 
    docker:
      - image: cimg/node:16.10
      - image: cimg/base:2021.09
    steps:
      # - checkout
      - run: 
          name: Install Netlify CLI
          command: npm install netlify-cli -g

      # Download and cache dependencies

      - run: 
          name: Install Dependencies
          command: npm install
      - run:
          name: Deploy at Netlify 
          command: npm run deploy
      - run: 
          name: Server Start
          command: npm run server:start
      
workflows:
  build_deploy:
    jobs: 
      - deploy